= Titre de l'article
Tristan Colombo
:chapeau: Ceci est le chapeau de l'article. \
Il s'agit d'une courte introduction au sujet ou à la problématique. \
Essayez d'être explicite et de donner envie au lecteur de poursuivre la lecture de l'article.
:keywords: Underscore.js, Javascript, Programmation fonctionnelle, Web, Python, Filtre
:short: Vous devez résumer ici le contenu de votre article, indiquer au lecteur tout ce qu’il pourra trouver dans les grandes lignes : \
Python est un langage multi-plateformes permettant de blabla blabla blabla. \
Dans ce contexte nous allons utiliser l’API XXXX de manière à créer une interface en mode texte. \
Nous verrons que ce n’est pas si simple, notamment à cause de la documentation qui blabla blablabla blabla blabla blablabla blabla. \
Malgré tout nous parviendrons à blabla blabla blabla blabla blabla blabla.
:sourcedir: includes
:codedir: code
:hide-uri-scheme:
:sectnums:
:experimental:
:numbered:

Un article commence *TOUJOURS* par une introduction qui n'est pas numérotée (regardez dans le magazine, il y a une lettrine sur la première lettre de cette section).
Sauf exception un article ne doit pas dépasser 12 pages dans le HS (si votre article est plus long c'est qu'il doit être traité sous la forme d'une suite d'articles).
Pour avoir une évaluation du nombre de pages qu'occupera votre article dans le magazine utilisez la macro `Stats_DiamondEditions()` fournie (ajoutez environ 1 page toute les 2 figures).

include::{sourcedir}/common.adoc[]
