= Titre de l'article (recette)
Tristan Colombo
:fonction: [Rédacteur en chef de GLMF]
:keywords: Underscore.js, Javascript, Programmation fonctionnelle, Web, Python, Filtre
:logos: Debian, Raspberry Pi, Github
:chapeau: Ceci est le chapeau de l'article. Il s'agit d'une courte introduction au sujet ou à la problématique. \
Essayez d'être explicite et de donner envie au lecteur de poursuivre la lecture de l'article.
:sourcedir: includes
:codedir: code
:hide-uri-scheme:
:experimental:

Il s'agit d'un format spécial d'article: pas de référence (il faudra mettre les liens dans le texte) ni de section "Pour aller plus loin" ni même d'introduction.
Le découpage de l'article est donné dans la suite.

Un article *ne doit pas dépasser 6 pages dans le magazine* (si votre article est plus long
c'est qu'il doit être traité sous la forme d'une suite d'articles).
Pour avoir une évaluation du nombre de pages qu'occupera votre article dans le magazine utilisez la macro `Stats_DiamondEditions()`
fournie (ajoutez environ 1 page toutes les 4 figures).

== L'objectif

Décrire ici l'objectif de l'article, qu'est-ce que l'on va chercher à réaliser
(le format est le même que pour les articles "standards": paragraphes en style "Normal", etc).

== Les outils

Décrire ici quels programmes vont être utilisés pour pouvoir parvenir au résultat.
Par exemple, pour décrire une installation/configuration d'Apache sous Debian il faudra seulement indiquer sous forme de liste:

- - un système GNU/Linux Debian (version utilisée dans l'article xxxxx)
- - `aptitude` (paquet `aptitude`)
- - `vim` (paquet `vim`) ou tout autre éditeur de code

== Phase 1

Déroulez les explications étape par étape. S'il s'agit d'un programme détachez bien les différentes phases
et enrichissez votre code étape par étape. On écrit un bout de code (ex de style pour du code dans du texte:
`fonction()`), on teste, ça marche et on passe à la suite. On améliore notre code (phase 2), on teste, etc.

include::{sourcedir}/blabla.adoc[]

include::{sourcedir}/bla.adoc[]

include::{sourcedir}/listing1.adoc[]

== Phase +++...+++

include::{sourcedir}/blabla.adoc[]

include::{sourcedir}/bla.adoc[]

include::{sourcedir}/session.adoc[]

== Phase n

include::{sourcedir}/blabla.adoc[]

include::{sourcedir}/bla.adoc[]

== Le résultat

On présente ici le résultat obtenu.

include::{sourcedir}/raccourcis.adoc[]
