== Titre de niveau 1

Paragraphe en style "Normal" (et non "Standard" ou "Corps de texte").

include::listings.adoc[]

Si vous souhaitez faire référence à des lignes de code pour les expliquer, vous pouvez les numéroter comme dans le code ci-dessus.
Essayez de commenter votre code et vos commandes shell de manière à ne pas avoir d'immenses blocs de code
ou de sorties shell qui rendent l'article illisible.

NOTE: /// Début note PAO ///

Le texte ici est destiné à indiquer des informations supplémentaires à la rédaction. Il n'apparaîtra pas dans l'article final.

NOTE: /// Fin note PAO ///

Pour une note apparaissant dans l'article final il faut seulement supprimer le terme PAO :

NOTE: /// Début note ///

Le texte présent ici, rédigé en style "Normal", apparaîtra dans l'article final dans une boîte spéciale "note".

NOTE: /// Fin note ///

Les indications en style "pragma", comme ci-dessus, doivent toujours être encadrées de 3 slashs /// ... ///.

Si vous souhaitez une note ayant pour titre: Avertissement ou Attention (avec la petite icône associée), il faut utiliser:

NOTE: /// Début note : Attention ///

Le texte présent ici, rédigé en style "Normal", apparaîtra dans l'article final dans une boîte spéciale "Attention".

NOTE: /// Fin note ///

NOTE: /// Début note : Avertissement ///

Le texte présent ici, rédigé en style "Normal", apparaîtra dans l'article final dans une boîte spéciale "Avertissement".

NOTE: /// Fin note ///

include::session.adoc[]

Le prompt en utilisateur standard est `$` et en root il s'agit de `#`.

NOTE: /// Début encadré ///

:!sectnums:

== Titre encadré

Vous pouvez créer des encadrés de quelques lignes pour expliquer,
définir des éléments de manière un peu plus pointue et/ou pour les mettre en exergue.

NOTE: /// Fin encadré ///

Plus d'informations sur GRUB sur le site officiel : http://www.gnu.org/software/grub/
(notez l'utilisation du style de caractère "url" et la désactivation de l'hyperlien).

include::liste-tableau.adoc[]

Les références, à mettre en style "gras", doivent être intégrées dans le discours du texte et leur étiquette sera un nombre
(attention à bien respecter un ordre croissant 1, 2, 3, etc.). Exemple: Comme on peut le voir sur le site de Linux Magazine *[1]*
et dans l'article de T. Colombo *[2]*, blablablabla blablabla. C'est seulement lorsqu'une citation apparaît dans le texte qu'elle peut être développée
dans la section "Références" en fin d'article. Dans cette section il faudra donner des références bibliographiques
ou des urls mais il faudra indiquer aussi à quoi elles correspondent (voir le format à respecter en fin d'article dans la section "Références").

N'intégrez pas vos images dans le fichier LibreOffice, mais faites-en mention avec le style "pragma".
Les fichiers images seront placés dans le même répertoire que l'article et leur nom sera composé à partir du nom de l'article et
de leur position dans celui-ci. Il devra en outre toujours être précédé d'un underscore. Vous devez également toujours faire référence
à une figure dans le texte : comme on peut le voir en figure 1, ... ou encore (voir figure 1)).

N'intégrez pas vos images dans le fichier OpenOffice, mais faites-en mention avec le style "pragma". Exemple:

include::image.adoc[]

include::menu.adoc[]

include::blabla.adoc[]

include::titraille.adoc[]

include::conclusion.adoc[]

== Références

- *[1]* Site officiel de _GNU/Linux Magazine_: http://www.gnulinuxmagazine.com
- *[2]* T. Colombo, _"Titre de l'article"_, _GNU/Linux Magazine_ n°171, Mai 2014, p. x à y.
- *[3]* P. Nom et A. Autrenom, _"Titre livre"_, éditeur, année.

Notez ci-dessus l'utilisation du style "italic" pour les titres de magazines. Les références doivent être écrites en style "Normal".

== Pour aller plus loin

Dans cette partie (*optionnelle*) vous pouvez donner une liste de liens, références bibliographiques sans les avoir cités dans le texte.
Attention, il faut tout de même un petit texte indiquant à quoi se rapporte le lien:

- Conférence de R. Stallman du 28 septembre 2012: https://www.youtube.com/watch?v=2onsOFWme-Q
- Le livre de R. Stallman, S. Williams et C. Masutti, _"Richard Stallman et la révolution du logiciel libre"_, Eyrolles, 2010.
